### ISSUE TITLE
[Help needed / support] Need a proper method to recover data

### ISSUE THREAD

**Issue by GameBurrow** [enakada/foxy-manga-reader#23]
So my windows broke down yesterday, causing me to reinstall it and due to that Firefox also. I have access to my old Firefox appdata folder, Foxy saved data locally. What is the proper method to move that over considering I can't do export/import.

When I tried just copying over storage.js from `browser-extension-data\foxy-manga-reader@enakada` it resulted in this:
![image](https://user-images.githubusercontent.com/4341091/45055584-e9460d80-b098-11e8-8fe6-c1542b44d445.png)

**Comment by enakada** [comment]
Hi there!

Foxy uses two types of storage, the one you copied has only the bookmark list and last read chapters (mostly due to this file having a size limit). The other one stores chapter data and other information.

If you have access to your previous AppData folder, try finding/copying the following folder as well:
- `path\to\AppData\Roaming\Mozilla\Firefox\Profiles\PROFILE_ID.default\storage\default\moz-extension+++91b818b3-2d62-4162-8479-5008e2426a4f`

Please tell me if this helps you restoring your data! :)

**Comment by GameBurrow** [comment]
Interesting I didn't had folder with that extension id or whatever that long number-letter combination is, only had the following:
![image](https://user-images.githubusercontent.com/4341091/45077622-51770c80-b0f6-11e8-93e4-cdcb2cca3490.png)
however both of these folders contents matched to what my new installation has so I copied contents over for both of those folders. No change.

These are insides for both those moz-extension folders:
![image](https://user-images.githubusercontent.com/4341091/45077746-a7e44b00-b0f6-11e8-9464-bebd3204081b.png) is one of them yours?

**Comment by enakada** [comment]
Hi there, I will be releasing an update today which will restore your database! I've found out that Firefox changed some things around in this new version (62.0) which will probably break Foxy for other users as well. I changed the add-on logic so that it will not happen again.

Edit: I also added a new 'Refresh Database' button in the dashboard page which will force a database update. When you finish updating the add-on, please use that button.
