### ISSUE TITLE
Restore Backup error

### ISSUE THREAD

**Issue by magecu** [enakada/foxy-manga-reader#4]
I get:
> An error occurred while restoring the backup file. Please contact the extension author.

I am attaching the ziped backup json file.

[foxy-manga-reader-2018110.zip](https://github.com/enakada/foxy-manga-reader/files/1619402/foxy-manga-reader-2018110.zip)

**Comment by enakada** [comment]
I found out what happened and I will be releasing a hotfix for this on monday.

Mangahere server is a little bit unstable these days. The problem is, if one of the manga fails to import, the whole restoration process will fail. I might have to change the import to a selective mode in which the user can select which ones to import, and can retry if it fails for network reasons.

**Comment by magecu** [comment]
Thank you. 
I can also parse the Json and remove the mangas from mangahere, for now.

Nice to know where is the problem coming from. 
And such a nice and fast response for a free extension.
Thank you again.
